version: '3'
services:

  # ✅ Kafka in KRaft mode (No Zookeeper required)
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"  # For inter-broker communication
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # This is not recommended in production
      CLUSTER_ID: "qQ82dM5sRCyOo4u1C5oUtg"  # Generated Cluster ID
    volumes:
      - ./data/kafka:/var/lib/kafka/data  # ✅ Kafka data persistence
    restart: always

  # ✅ MySQL Service with Persistent Data Storage
  mysql:
    image: mysql:9.2
    container_name: mysql-container
    ports:
      - "3306:3306"  # Expose MySQL to the host machine
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: applix_db  # ✅ Auto-create `applix_db` on startup
      MYSQL_USER: applix
      MYSQL_PASSWORD: applix123
    volumes:
      - ./data/mysql:/var/lib/mysql  # ✅ MySQL data persistence
    restart: always